from typing import Protocol
from vision.types import FramePacket, DetectionResult


class BaseDetector(Protocol):
    def load_model(self, path: str | None = None) -> None: ...
    def predict(self, packet: FramePacket) -> DetectionResult: ...
    def reset(self) -> None: ...
